import { BlockConfig, BlockId, Item, Recipe } from './types';

export const TILE_SIZE = 24;
export const WORLD_WIDTH = 160;
export const WORLD_HEIGHT = 90;
export const REACH_DISTANCE = 180;

// Physics constants
export const GRAVITY = 0.42;
export const MAX_FALL_SPEED = 12;
export const MOVE_SPEED = 3.4;
export const MOVE_ACCEL = 0.6;
export const FRICTION = 0.82;
export const AIR_FRICTION = 0.94;
export const JUMP_FORCE = -8.2;

// Blocks database
export const BLOCKS: Record<BlockId, BlockConfig> = {
  air: {
    id: 'air',
    name: 'Воздух',
    hardness: 0,
    solid: false,
    color: 'transparent',
  },
  grass: {
    id: 'grass',
    name: 'Дёрн с травой',
    hardness: 1.0,
    solid: true,
    dropItemId: 'dirt',
    dropCount: 1,
    color: '#4ade80',
    detailColor: '#78350f',
  },
  dirt: {
    id: 'dirt',
    name: 'Земля',
    hardness: 1.0,
    solid: true,
    dropItemId: 'dirt',
    dropCount: 1,
    color: '#854d0e',
    detailColor: '#713f12',
  },
  stone: {
    id: 'stone',
    name: 'Камень',
    hardness: 2.5,
    solid: true,
    dropItemId: 'stone',
    dropCount: 1,
    color: '#64748b',
    detailColor: '#475569',
  },
  sand: {
    id: 'sand',
    name: 'Песок',
    hardness: 0.8,
    solid: true,
    dropItemId: 'sand',
    dropCount: 1,
    color: '#fde047',
    detailColor: '#eab308',
  },
  wood: {
    id: 'wood',
    name: 'Древесина',
    hardness: 1.8,
    solid: true,
    dropItemId: 'wood',
    dropCount: 1,
    color: '#b45309',
    detailColor: '#78350f',
  },
  leaves: {
    id: 'leaves',
    name: 'Листва',
    hardness: 0.5,
    solid: false,
    dropItemId: 'leaves',
    dropCount: 1,
    color: '#16a34a',
    detailColor: '#15803d',
  },
  copper_ore: {
    id: 'copper_ore',
    name: 'Медная руда',
    hardness: 3.2,
    solid: true,
    dropItemId: 'copper_ore',
    dropCount: 1,
    color: '#64748b',
    accentColor: '#f97316',
    detailColor: '#ea580c',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Железная руда',
    hardness: 4.0,
    solid: true,
    dropItemId: 'iron_ore',
    dropCount: 1,
    color: '#475569',
    accentColor: '#cbd5e1',
    detailColor: '#94a3b8',
  },
  brick: {
    id: 'brick',
    name: 'Каменный кирпич',
    hardness: 3.0,
    solid: true,
    dropItemId: 'brick',
    dropCount: 1,
    color: '#94a3b8',
    detailColor: '#475569',
  },
  crystal: {
    id: 'crystal',
    name: 'Био-кристалл',
    hardness: 5.0,
    solid: true,
    dropItemId: 'crystal',
    dropCount: 1,
    color: '#06b6d4',
    accentColor: '#a5f3fc',
    detailColor: '#0891b2',
    lightEmission: 0.8,
  },
  abyss_stone: {
    id: 'abyss_stone',
    name: 'Абиссальный камень',
    hardness: 6.5,
    solid: true,
    dropItemId: 'abyss_stone',
    dropCount: 1,
    color: '#312e81',
    accentColor: '#818cf8',
    detailColor: '#1e1b4b',
    lightEmission: 0.3,
  },
  altar: {
    id: 'altar',
    name: 'Древний алтарь',
    hardness: 8.0,
    solid: true,
    dropItemId: 'stone',
    dropCount: 5,
    color: '#7c3aed',
    accentColor: '#c084fc',
    lightEmission: 0.9,
  },
};

// All game items
export const ITEMS: Record<string, Item> = {
  // Tools & Weapons
  wooden_pickaxe: {
    id: 'wooden_pickaxe',
    name: 'Деревянная кирка',
    type: 'tool',
    description: 'Базовый инструмент для добычи земли и камня.',
    stackable: false,
    maxStack: 1,
    pickaxePower: 1.0,
    damage: 4,
    attackSpeed: 300,
    iconType: 'pickaxe',
    color: '#b45309',
  },
  copper_pickaxe: {
    id: 'copper_pickaxe',
    name: 'Медная кирка',
    type: 'tool',
    description: 'Прочная кирка, быстрее разрушает плотные породы.',
    stackable: false,
    maxStack: 1,
    pickaxePower: 2.2,
    damage: 7,
    attackSpeed: 240,
    iconType: 'pickaxe',
    color: '#f97316',
  },
  crystal_drill: {
    id: 'crystal_drill',
    name: 'Кристальный бур',
    type: 'tool',
    description: 'Высокотехнологичный бур из кристаллов глубин. Молниеносно бурит любые блоки.',
    stackable: false,
    maxStack: 1,
    pickaxePower: 4.5,
    damage: 15,
    attackSpeed: 160,
    iconType: 'drill',
    color: '#06b6d4',
  },
  wooden_axe: {
    id: 'wooden_axe',
    name: 'Боевой топор лесоруба',
    type: 'tool',
    description: 'Тяжелый боевой топор. Сокрушительный рубящий урон (22 ед.) и мгновенная рубка деревьев!',
    stackable: false,
    maxStack: 1,
    axePower: 2.0,
    damage: 22,
    attackSpeed: 330,
    range: 58,
    iconType: 'axe',
    color: '#b45309',
  },
  copper_axe: {
    id: 'copper_axe',
    name: 'Медная боевая секира',
    type: 'tool',
    description: 'Острая тяжелая секира из закаленной меди. Огромный рубящий урон (36 ед.) с широким размахом!',
    stackable: false,
    maxStack: 1,
    axePower: 3.5,
    damage: 36,
    attackSpeed: 290,
    range: 64,
    iconType: 'axe',
    color: '#ea580c',
  },
  abyss_axe: {
    id: 'abyss_axe',
    name: 'Абиссальный топор палача',
    type: 'tool',
    description: 'Легендарная секира глубин с кристальным лезвием. Наносит 62 единицы сокрушительного урона!',
    stackable: false,
    maxStack: 1,
    axePower: 5.0,
    damage: 62,
    attackSpeed: 250,
    range: 72,
    iconType: 'axe',
    color: '#8b5cf6',
  },
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Деревянный клинок',
    type: 'weapon',
    description: 'Простое оружие для защиты от первых слизней.',
    stackable: false,
    maxStack: 1,
    damage: 8,
    attackSpeed: 320,
    range: 48,
    iconType: 'sword',
    color: '#d97706',
  },
  copper_sword: {
    id: 'copper_sword',
    name: 'Медный тесак',
    type: 'weapon',
    description: 'Острый клинок из закаленной меди.',
    stackable: false,
    maxStack: 1,
    damage: 16,
    attackSpeed: 280,
    range: 54,
    iconType: 'sword',
    color: '#ea580c',
  },
  abyss_blade: {
    id: 'abyss_blade',
    name: 'Абиссальный рассекатель',
    type: 'weapon',
    description: 'Легендарное оружие глубин. Наносит сокрушительный урон с импульсом энергии.',
    stackable: false,
    maxStack: 1,
    damage: 32,
    attackSpeed: 220,
    range: 65,
    iconType: 'sword',
    color: '#818cf8',
  },

  // Blocks items
  dirt: {
    id: 'dirt',
    name: 'Земляной блок',
    type: 'block',
    description: 'Обычный блок плодородной почвы.',
    blockId: 'dirt',
    stackable: true,
    maxStack: 99,
    iconType: 'block',
    color: '#854d0e',
  },
  stone: {
    id: 'stone',
    name: 'Каменный блок',
    type: 'block',
    description: 'Крепкий серый камень.',
    blockId: 'stone',
    stackable: true,
    maxStack: 99,
    iconType: 'block',
    color: '#64748b',
  },
  sand: {
    id: 'sand',
    name: 'Песок',
    type: 'block',
    description: 'Рассыпчатый золотой песок.',
    blockId: 'sand',
    stackable: true,
    maxStack: 99,
    iconType: 'block',
    color: '#fde047',
  },
  wood: {
    id: 'wood',
    name: 'Древесина',
    type: 'block',
    description: 'Стволы деревьев. Основной строительный материал.',
    blockId: 'wood',
    stackable: true,
    maxStack: 99,
    iconType: 'block',
    color: '#b45309',
  },
  leaves: {
    id: 'leaves',
    name: 'Листва',
    type: 'block',
    description: 'Зеленая листва деревьев.',
    blockId: 'leaves',
    stackable: true,
    maxStack: 99,
    iconType: 'block',
    color: '#16a34a',
  },
  copper_ore: {
    id: 'copper_ore',
    name: 'Медная руда',
    type: 'material',
    description: 'Кусочки медной руды. Нужна для ковки медного снаряжения.',
    blockId: 'copper_ore',
    stackable: true,
    maxStack: 99,
    iconType: 'ore',
    color: '#f97316',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Железная руда',
    type: 'material',
    description: 'Плотный металл из глубин земли.',
    blockId: 'iron_ore',
    stackable: true,
    maxStack: 99,
    iconType: 'ore',
    color: '#94a3b8',
  },
  brick: {
    id: 'brick',
    name: 'Каменный кирпич',
    type: 'block',
    description: 'Обработанные каменные блоки для строительства базы.',
    blockId: 'brick',
    stackable: true,
    maxStack: 99,
    iconType: 'block',
    color: '#94a3b8',
  },
  crystal: {
    id: 'crystal',
    name: 'Био-кристалл',
    type: 'block',
    description: 'Светящийся кристалл с высокой плотностью энергии.',
    blockId: 'crystal',
    stackable: true,
    maxStack: 99,
    iconType: 'crystal',
    color: '#06b6d4',
  },
  abyss_stone: {
    id: 'abyss_stone',
    name: 'Абиссальный камень',
    type: 'block',
    description: 'Тяжелый фиолетовый монолит из самой опасной зоны.',
    blockId: 'abyss_stone',
    stackable: true,
    maxStack: 99,
    iconType: 'block',
    color: '#312e81',
  },

  // Monster Drops & Materials
  slime_gel: {
    id: 'slime_gel',
    name: 'Слизь',
    type: 'material',
    description: 'Вязкая субстанция, выпадающая со слизней.',
    stackable: true,
    maxStack: 99,
    iconType: 'drop',
    color: '#22c55e',
  },
  royal_core: {
    id: 'royal_core',
    name: 'Ядро Королевского Геля',
    type: 'material',
    description: 'Трофей победы над первым боссом. Пульсирует чистой энергией.',
    stackable: true,
    maxStack: 10,
    iconType: 'core',
    color: '#eab308',
  },
  spore: {
    id: 'spore',
    name: 'Био-спора',
    type: 'material',
    description: 'Левитирующая спора летучих паразитов.',
    stackable: true,
    maxStack: 99,
    iconType: 'drop',
    color: '#a855f7',
  },
  chitin: {
    id: 'chitin',
    name: 'Панцирный хитин',
    type: 'material',
    description: 'Прочный панцирь пещерного монстра.',
    stackable: true,
    maxStack: 99,
    iconType: 'drop',
    color: '#f43f5e',
  },
  abyss_heart: {
    id: 'abyss_heart',
    name: 'Сердце Бездны',
    type: 'material',
    description: 'Финальный артефакт победы над Кристальным Колоссом!',
    stackable: true,
    maxStack: 5,
    iconType: 'heart',
    color: '#ec4899',
  },

  // Consumables & Summons
  healing_gel: {
    id: 'healing_gel',
    name: 'Лечебный био-гель',
    type: 'consumable',
    description: 'Восстанавливает 40 единиц здоровья Амёбы при нажатии ПКМ.',
    stackable: true,
    maxStack: 20,
    healAmount: 40,
    iconType: 'flask',
    color: '#10b981',
  },
  boss_summon_1: {
    id: 'boss_summon_1',
    name: 'Корона Слизевика',
    type: 'summon',
    description: 'Призывает босса «Королевский Гель». Используйте ПКМ на поверхности!',
    stackable: true,
    maxStack: 5,
    iconType: 'crown',
    color: '#fbbf24',
  },
  boss_summon_2: {
    id: 'boss_summon_2',
    name: 'Око Пещерного Стража',
    type: 'summon',
    description: 'Призывает могущественного босса «Кристальный Колосс». Используйте ПКМ!',
    stackable: true,
    maxStack: 5,
    iconType: 'eye',
    color: '#8b5cf6',
  },
};

// Crafting Recipes
export const RECIPES: Recipe[] = [
  {
    id: 'craft_wood_pickaxe',
    name: 'Деревянная кирка',
    result: { itemId: 'wooden_pickaxe', count: 1 },
    ingredients: [{ itemId: 'wood', count: 5 }],
  },
  {
    id: 'craft_wood_sword',
    name: 'Деревянный меч',
    result: { itemId: 'wooden_sword', count: 1 },
    ingredients: [{ itemId: 'wood', count: 6 }],
  },
  {
    id: 'craft_wood_axe',
    name: 'Боевой деревянный топор',
    result: { itemId: 'wooden_axe', count: 1 },
    ingredients: [{ itemId: 'wood', count: 5 }],
  },
  {
    id: 'craft_copper_axe',
    name: 'Медная боевая секира',
    result: { itemId: 'copper_axe', count: 1 },
    ingredients: [
      { itemId: 'copper_ore', count: 10 },
      { itemId: 'wood', count: 4 },
    ],
  },
  {
    id: 'craft_abyss_axe',
    name: 'Абиссальный топор палача',
    result: { itemId: 'abyss_axe', count: 1 },
    ingredients: [
      { itemId: 'royal_core', count: 1 },
      { itemId: 'chitin', count: 6 },
      { itemId: 'crystal', count: 6 },
      { itemId: 'wood', count: 5 },
    ],
  },
  {
    id: 'craft_brick',
    name: 'Каменный кирпич (x4)',
    result: { itemId: 'brick', count: 4 },
    ingredients: [{ itemId: 'stone', count: 4 }],
  },
  {
    id: 'craft_healing_gel',
    name: 'Лечебный био-гель',
    result: { itemId: 'healing_gel', count: 1 },
    ingredients: [
      { itemId: 'slime_gel', count: 2 },
      { itemId: 'wood', count: 1 },
    ],
  },
  {
    id: 'craft_copper_pickaxe',
    name: 'Медная кирка',
    result: { itemId: 'copper_pickaxe', count: 1 },
    ingredients: [
      { itemId: 'copper_ore', count: 8 },
      { itemId: 'wood', count: 4 },
    ],
  },
  {
    id: 'craft_copper_sword',
    name: 'Медный тесак',
    result: { itemId: 'copper_sword', count: 1 },
    ingredients: [
      { itemId: 'copper_ore', count: 10 },
      { itemId: 'wood', count: 3 },
    ],
  },
  {
    id: 'craft_boss1_summon',
    name: 'Корона Слизевика (Призыв Босса 1)',
    result: { itemId: 'boss_summon_1', count: 1 },
    ingredients: [
      { itemId: 'slime_gel', count: 8 },
      { itemId: 'copper_ore', count: 3 },
    ],
  },
  {
    id: 'craft_boss2_summon',
    name: 'Око Пещерного Стража (Призыв Босса 2)',
    result: { itemId: 'boss_summon_2', count: 1 },
    ingredients: [
      { itemId: 'royal_core', count: 1 },
      { itemId: 'crystal', count: 5 },
      { itemId: 'spore', count: 4 },
    ],
  },
  {
    id: 'craft_crystal_drill',
    name: 'Кристальный бур',
    result: { itemId: 'crystal_drill', count: 1 },
    ingredients: [
      { itemId: 'royal_core', count: 1 },
      { itemId: 'crystal', count: 8 },
      { itemId: 'copper_ore', count: 5 },
    ],
  },
  {
    id: 'craft_abyss_blade',
    name: 'Абиссальный рассекатель',
    result: { itemId: 'abyss_blade', count: 1 },
    ingredients: [
      { itemId: 'royal_core', count: 1 },
      { itemId: 'chitin', count: 6 },
      { itemId: 'crystal', count: 6 },
    ],
  },
];
